import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    width: "95%", 
    alignSelf: "center",
    marginBottom: 16,
    borderRadius: 10,
    backgroundColor: "#fff", 
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
    overflow: "hidden",
    paddingBottom: 16, 
  },
  imageContainer: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    overflow: "hidden",
    position: "relative", 
  },
  image: {
    width: "80%",
    height: "100%",
    resizeMode: "cover",
    alignSelf: "center",
    marginTop: 15,
    borderRadius: 10,
  },
  titleContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  title: {
    fontSize: 16,
    fontFamily: "Poppins-Bold",
    color: "#333",
    textAlign: "center",
  },
  iconContainer: {
    position: "absolute",
    top: 10, 
    right: 0, 
    zIndex: 10,
    borderRadius: 50,
    padding: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4, 
  },
});
