import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
    backgroundColor: "#F8F8F8",
  },
  box: {
    width: "90%",
    padding: 20,
    borderWidth: 1,
    borderColor: "#3DA510",
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
    alignItems: "center",
  },
  title: {
    fontFamily: "Poppins-Bold",
    fontSize: 24,
    marginBottom: 16,
    color: "#737373",
  },
  inputContainer: {
    width: "100%",
    marginVertical: 10,
  },
  label: {
    fontFamily: "Poppins",
    fontSize: 14,
    color: "#737373",
    marginBottom: 5,
    fontWeight: "600",
  },
  input: {
    padding: 10,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: "#ccc",
    color: "#000",
    fontFamily: "Poppins",
    fontSize: 14,
  },
  authButton: {
    width: "100%",
    padding: 15,
    backgroundColor: "#FF6F61",
    borderRadius: 5,
    marginVertical: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  authButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontFamily: "Poppins-Bold",
    fontWeight: "bold",
  },
  switchButton: {
    marginTop: 10,
    alignItems: "center",
  },
  switchButtonText: {
    fontSize: 14,
    fontFamily: "Poppins",
  },
  primaryText: {
    color: "#FF6F61",
    fontSize: 12,
    textDecorationLine: "underline",
    textDecorationStyle: "double",
  },
  highlight: {
    color: "#3DA510",
    fontSize: 13,
    fontFamily: "Poppins-Bold",
    textDecorationLine: "underline",
    textDecorationColor: "#FF6F61",
    textDecorationStyle: "double",
  },
  authGoogle: {
    width: "100%",
    padding: 15,
    borderRadius: 5,
    marginVertical: 10,
    alignItems: "center",
    color: "#545454",
    shadowColor: "#3DA510",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  authGoogleButtonText: {
    color: "545454",
    fontFamily:"Poppins"
  },
});
